<?php

namespace AppBundle\Repository;

/**
 * CervezaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CervezaRepository extends \Doctrine\ORM\EntityRepository
{
}
