<?php

namespace AppBundle\Repository;

/**
 * CervezaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CervezaRepository extends \Doctrine\ORM\EntityRepository
{
  public function getDestacadas()
  {
    return $this->getEntityManager()
            ->createQuery(
                'SELECT c FROM AppBundle:Cerveza c where c.destacada = TRUE')
            ->getResult();
  }

  public function getPorOrigen($origen)
  {
    return $this->getEntityManager()
            ->createQuery(
                'SELECT c FROM AppBundle:Cerveza c where c.origen = :origen')
            ->setParameter('origen', $origen)
            ->getResult();
  }
}
