<?php

namespace AppBundle\Repository;

/**
 * EstiloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstiloRepository extends \Doctrine\ORM\EntityRepository
{
}
