<?php

namespace AppBundle\Repository;

/**
 * PedidoCervezaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PedidoCervezaRepository extends \Doctrine\ORM\EntityRepository
{
}
